apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/postgres-configmap.yaml
- manifests/postgres.yaml
- manifests/persistentvolume.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/configmap.yaml
- manifests/logoutput-service.yaml
- manifests/deployment.yaml
- manifests/pingpong-service.yaml
- manifests/pingpong-deployment.yaml
- manifests/ingress.yaml
- manifests/resourcequota.yaml
images:
- name: LOGOUTPUT_IMAGE
  newName: juhosii/devops-kubernetes
  newTag: ce8d053b4196db0bff57d174975263f72a9c2796
- name: PINGPONG_IMAGE
  newName: juhosii/devops-kubernetes
  newTag: ce8d053b4196db0bff57d174975263f72a9c2796-PINGPONG
