apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/postgres-configmap.yaml
- manifests/postgres.yaml
- manifests/persistentvolume.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/configmap.yaml
- manifests/logoutput-service.yaml
- manifests/deployment.yaml
- manifests/pingpong-service.yaml
- manifests/pingpong-deployment.yaml
- manifests/ingress.yaml
images:
- name: LOGOUTPUT_IMAGE
  newName: juhosii/devops-kubernetes
  newTag: 228c0472b5b0de45f70a101725fb6d969ea7bf54
- name: PINGPONG_IMAGE
  newName: juhosii/devops-kubernetes
  newTag: 228c0472b5b0de45f70a101725fb6d969ea7bf54-PINGPONG
