apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/postgres-configmap.yaml
- manifests/postgres.yaml
- manifests/persistentvolume.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/configmap.yaml
- manifests/logoutput-service.yaml
- manifests/deployment.yaml
- manifests/pingpong-service.yaml
- manifests/pingpong-deployment.yaml
- manifests/ingress.yaml
images:
- name: LOGOUTPUT_IMAGE
  newName: juhosii/devops-kubernetes
  newTag: ec58ca01aa2cca57efba87be203e657bc774be9a
- name: PINGPONG_IMAGE
  newName: juhosii/devops-kubernetes
  newTag: ec58ca01aa2cca57efba87be203e657bc774be9a-PINGPONG
