apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/postgres-configmap.yaml
- manifests/postgres.yaml
- manifests/persistentvolume.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/configmap.yaml
- manifests/logoutput-service.yaml
- manifests/deployment.yaml
- manifests/pingpong-service.yaml
- manifests/pingpong-deployment.yaml
- manifests/ingress.yaml
- manifests/resourcequota.yaml
images:
- name: LOGOUTPUT_IMAGE
  newName: juhosii/devops-kubernetes
  newTag: c5e5c6282ab36968cf1ea8746e5774534a15932f
- name: PINGPONG_IMAGE
  newName: juhosii/devops-kubernetes
  newTag: c5e5c6282ab36968cf1ea8746e5774534a15932f-PINGPONG
